config/routes.rb
Rails.application.routes.draw do
  root 'welcome#hello'
  #Posts
  get 'post/new' => 'posts#new', as: :new_post
  post 'posts' => 'posts#create'
  get 'post/:id' => 'posts#detail', as: :post
  get 'post/:id/edit' => 'posts#edit', as: :edit_post
  patch 'post/:id' => 'posts#update', as: :update_post
  delete 'post/:id' => 'posts#delete', as: :delete_post
  get 'post/:id/detail' =>'posts#show', as: :show_post
  get 'posts' => 'posts#index', as: :all_posts

#Sessions
  get 'sign_in' => 'sessions#new', as: :sign_in
  post 'sign_in' => 'sessions#create'
  delete 'sign_out' => 'sessions#delete', as: :end_session
  get 'sign_out' => 'sessions#delete', as: :sign_out

#users
  get 'register' => 'users#new', as: :new_user
  post 'register' => 'users#create', as: :create_user
  get 'users' => 'users#index', as: :users
  get 'entourage' => 'users#following', as: :following
  post 'follow/:user_id' => 'users#follow', as: :follow
  post 'unfollow/:user_id' => 'users#unfollow', as: :unfollow

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_followable
  acts_as_follower

  has_many :posts, dependent: :destroy

  has_secure_password

  validates :name, :email,  presence: true
  validates :name, :email,  uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_action :authenticate_user!

  before_action do
    if @current_user.nil?
      redirect_to sign_in_path, alert: "Please sign in."
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new
    @post.message = params[:post][:message]
    @post.user = @current_user

    if @post.save
     redirect_to root_path, notice: "Gauzip Whispered!"
    else
     render :new
   end
  end

  def edit
     @post = Post.find_by id: params[:id]
  end

  def update
    @post = Post.find_by id: params[:id]
    @post.message = params[:post][:message]
    if @post.save
     redirect_to root_path, notice: "Gauzip Updated!"
    else
     render :edit
    end
  end


  def delete
      @post = Post.find_by id: params[:id]
      @post.destroy
      redirect_to root_path, notice: "Gauzip deleted. History altered!"
  end

  def index
    @posts = Post.all
  end

  def detail
    @post = Post.find_by id: params[:id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create

    user = User.find_by name: params[:name]
    if user && user.authenticate(params[:password])
      # make session[:name] present
      session[:user_id] = user.id
      redirect_to root_path, notice: "Welcome to Gauzip!"
    else
      flash.now[:alert] = "Something is wrong with your username and/or password"
      render :new
    end
  end

  def delete
    # we should sign out
    # make future tests if we are signed in fail
    session.delete :user_id
    redirect_to root_path, notice: "Signed Out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
      @user = User.new
    end

    def create
      @user = User.new user_params
      if @user.save
        session[:user_id] = @user.id
        redirect_to root_path
      else
        render :new
      end
    end

    def index
       @users = User.where("id != ?", @current_user.id)
   end

    def following
     @users = @current_user.following_users
   end

   def follow
     # do the thing
     user = User.find_by! id: params[:user_id]
     @current_user.follow(user)
     redirect_to users_path, notice: "✅✅"
   end

   def unfollow
     user = User.find_by! id: params[:user_id]
     @current_user.stop_following(user)
     redirect_to users_path, notice: "👻👻"
   end


  def user_params
     params.require(:user).permit(:email, :name,  :password)
 end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def hello
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<link href="https://fonts.googleapis.com/css?family=Parisienne" rel="stylesheet"> </head>
<body>
  <div class="row">
    <div class="col-xs-12, col-sm-6, col-lg-8">
      <div class="header_bar">
        <h1><%=link_to 'Gauzip', root_path%><i class="fa fa-bullhorn" aria-hidden="true"></i></h1>
      </div>
    </div>
  <div class="col-xs-6, col-lg-4">
    <div class="header_bar">
      <div class="header_links">
          <%if @current_user!=nil%>
          <%=link_to 'Share Gossip', new_post_path%> -
          <%=link_to 'Get Gossip', root_path%> -
          <%=link_to 'Sign Out', sign_out_path%> -
          <%= link_to 'All Users', users_path %>   -
          <%= link_to 'Your Clique', following_path %> -
            <%else%>
            <%=link_to 'Sign In', sign_in_path%>  or  
            <%=link_to 'Sign Up', new_user_path%>
            <%end%>
          </div>
        </div>
      </div>

  </div>


<div class="container">


    <% if alert %>
      <div class="alert alert-danger"><%= alert %></div>
    <% end %>

    <% if notice %>
      <div class="alert alert-info"><%= notice %></div>
  <% end %>

</div>
<div class="yield-container">
  <%= yield %>
</div>

<div class="footer">

  <i class="fa fa-copyright" aria-hidden="true"></i> 2016 <br/>
  S. D O S S E T T  S W I F T<br/>

<i class="fa fa-code" aria-hidden="true"></i> fueled by <i class="fa fa-heart" aria-hidden="true"></i>, <i class="fa fa-coffee" aria-hidden="true"></i>
, and <a href="https://github.com/sdossettswift/twitter_clone"><i class="fa fa-github" aria-hidden="true"></i></a>

</div>
</body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/delete.html.erb
<h1>Posts#delete</h1>
<p>Find me in app/views/posts/delete.html.erb</p>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/users/following.html.erb
<div class="page-header">
  <h1>People You Follow</h1>
</div>


<div class="list-group">
  <% @users.each do |user| %>
    <div class="list-group-item">
      <%= user.name %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="page-header">
  <h2>The Posse</h2>
</div>

<div class="list-group">
  <% @users.each do |user| %>
    <div class="list-group-item">
      <%= user.username %> -
        <% if @current_user.following?(user) %>
          <%= link_to "Ghost #{user.username}", unfollow_path(user_id: user.id), method: :post, class: "btn btn-primary" %>
        <% else %>
          <%= link_to "Follow #{user.username}", follow_path(user_id: user.id), method: :post, class: "btn btn-primary" %>
        <% end %>
    </div>
  <% end %>

</div>

app/views/users/new.html.erb
<div class="page-header">
  <h2>You want to sit with us?</h2>
</div>

<div class="container">
  <% if @user.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <% @user.errors.full_messages.each do |msg| %>
        <%= msg %><br>
      <% end %>
    </div>
  <% end %>

  <div class="well">
      <%= form_for @user, url: new_user_path do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.submit class: "btn btn-lg btn-info" %>
        </div>

          or
          <%= link_to "Sign In", root_path %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

app/views/welcome/hello.html.erb
<h1>Welcome to Gauzip!</h1>